dogsitter/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dogsitter_core.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dogsitter_core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import date
from multiselectfield import MultiSelectField


class Profile(models.Model):
    user = models.OneToOneField(User, models.CASCADE)
    location = models.CharField(max_length=1000)
    bio = models.TextField(max_length=1000000)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return str(self.user)


class DogSitterProfile(models.Model):
    ALONE = 'alone'
    WITH_SPOUSE = 'with_spouse'
    WITH_ROOMMATES = 'with_roommates'
    WITH_SPOUSE_CHILDREN = 'with_spouse_and_children'
    WITH_CHILDREN = 'with_children'

    LIVING_ARRANGEMENTS = [
        (ALONE, 'I live alone'),
        (WITH_SPOUSE, 'I live with my spouse/partner'),
        (WITH_ROOMMATES, 'I live with roommates'),
        (WITH_SPOUSE_CHILDREN, 'I live with my spouse and children'),
        (WITH_CHILDREN, 'I live with children')
    ]

    HOUSE = 'house'
    APARTMENT = 'apartment'
    CONDO = 'condo'
    ALTERNATIVE = 'alternative'

    HOUSE_CHOICES = [
        (HOUSE, 'I live in a house'),
        (APARTMENT, 'I live in an apartment'),
        (CONDO, 'I live in a condo'),
        (ALTERNATIVE, 'I live in an alternative style of housing'),
    ]

    SMALL = "small"
    MEDIUM = "medium"
    LARGE = "large"
    EXTRA_LARGE = "extra_large"

    DOG_SIZES = [
        (SMALL, "Small Dogs (up to 22lbs)"),
        (MEDIUM, "Medium Dogs (23lbs to 55lbs)"),
        (LARGE, "Large Dogs (up to 100lbs)"),
        (EXTRA_LARGE, "Extra Large Dogs (over 100lbs)"),
    ]

    ZERO_ = 'zero'
    UP_TO_TWO = 'two_hours'
    UP_TO_FOUR = 'four_hours'
    UP_TO_EIGHT = 'eight_hours'

    HOURS_CHOICES = [
        (ZERO_, 'Your dog will not be left alone'),
        (UP_TO_TWO, 'Up to two hours'),
        (UP_TO_FOUR, 'Up to four hours'),
        (UP_TO_EIGHT, 'Up to eight hours'),
    ]

    ONE = 'one'
    TWO = 'two'
    TWO_PLUS = 'more than two'

    WALK_CHOICES = [
        (ONE, 'One'),
        (TWO, 'Two'),
        (TWO_PLUS, 'More than two'),
    ]

    DOGBED = 'dogbed'
    BED = 'bed'
    COUCH = 'couch'
    ANYWHERE = 'anywhere'

    SLEEPING_CHOICES = [
        (DOGBED, 'On a dogbed'),
        (BED, 'On the bed'),
        (COUCH, 'On the couch'),
        (ANYWHERE, 'Wherever they would like'),
    ]

    user = models.OneToOneField(User, models.CASCADE)
    living_arrangements = models.CharField(max_length=1000,
                                           choices=LIVING_ARRANGEMENTS, default="")
    housing = models.CharField(max_length=1000, choices=HOUSE_CHOICES, default="")
    yard = models.BooleanField(default=False)
    cost = models.DecimalField(decimal_places=2, max_digits=7)
    dog_sizes = MultiSelectField(choices=DOG_SIZES, default='')
    hours_alone = models.CharField(max_length=1000, choices=HOURS_CHOICES, default="")
    walks = models.CharField(max_length=1000, choices=WALK_CHOICES, default="")
    sleeping_arrangements = models.CharField(max_length=1000, choices=SLEEPING_CHOICES, default="")


class Dog(models.Model):
    user = models.ForeignKey(User, models.CASCADE)
    name = models.CharField(max_length=200)
    weight = models.IntegerField()
    good_with_cats = models.BooleanField(default=False)
    good_with_kids = models.BooleanField(default=False)
    good_with_dogs = models.BooleanField(default=False)
    bio = models.TextField(max_length=100000)
    dob = models.DateField()
    breed = models.CharField(max_length=1000)
    image = models.ImageField(default='DogProfile.png', upload_to='dog_pics')

    def __str__(self):
        return str(self.name)

    def age(self):
        time_lived = timezone.now().date() - self.dob
        months_lived = time_lived.days//30.5
        if months_lived < 1:
            return f'{time_lived.days} days'
        if months_lived < 12:
            return f'{int(months_lived)} months'
        elif months_lived < 24:
            return f'{int(months_lived//12)} years and {int(months_lived%12)} months'
        else:
            return f'{int(months_lived)//12} years'

    def is_birthday_today(self):
        date_today = date.today()
        day = date_today.day
        month = date_today.month
        birth_day = self.dob.day
        birth_month = self.dob.month
        return day == birth_day and month == birth_month


class GalleryImage(models.Model):
    user = models.ForeignKey(User, models.CASCADE)
    image = models.ImageField(upload_to='profile_pics')


class DogGalleryImage(models.Model):
    dog = models.ForeignKey(Dog, models.CASCADE)
    image = models.ImageField(upload_to='dog_pics')

templates/add_images.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Add Images
{% endblock %}

{% block content %}
    <form method = "POST" enctype="multipart/form-data" >
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="top-buttons">
    </form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{%block title%}{%endblock title%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cantarell:wght@400;700&family=Shrikhand&display=swap" rel="stylesheet">
<style>
    {% block extra_css %}{% endblock %}
</style>
</head>
<body>
    <header class="main-header">
        <div class="nav-container">
            <a href="{% url 'home' %}">
                <h1 class="header-title"> DogSitters</h1>
            </a>
            <div class="main-nav">
                <button class="top-buttons"><a href= "{% url 'home' %}">Home</a></button>
                {% if user.is_authenticated %}
                    <button class="top-buttons"><a href= "{% url 'logout' %}">Logout</a></button>
                {% else %}
                    <button class="top-buttons"><a href= "{% url 'login' %}">Login</a></button>
                    <button class="top-buttons"><a href= "{% url 'register' %}">Sign Up</a></button>
                {% endif %}
                {% if user.is_authenticated and user.profile.image %}
                <div class="dropdown">
                    <img class="nav_profile_pic" src="{{ user.profile.image.url}}" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li><a class="dropdown-item" href="{% url 'profile_page' user.profile.pk %}">Profile Page</a></li>
                            <li><a class="dropdown-item" href="{% url 'add_dog' %}">Add your Dogs</a></li>
                        {% if user.dogsitterprofile %}
                        <li><a class="dropdown-item" href="{% url 'edit_dogsitter_profile' %}">Update Dogsitting Information </a></li>
                        {% else %}
                        <li><a class="dropdown-item" href="{% url 'create_dogsitter_profile' %}">Become a Dogsitter</a></li
                        {% endif %}
                        <li><a class="dropdown-item" href="{% url 'edit_info' %}">Update username</a></li>
                        <li><a class="dropdown-item" href="{% url 'change_password' %}">Change Password</a></li>
                    </div>
                {% endif %}
            </div>
        </div>
    </header>
    {% for message in messages %}
        <div class="message">{{message}}</div>
    {% endfor %}
    {% block content_nocontainer %}

        <div class="container">
            {% block content %}{% endblock content %}
        </div>
    {% endblock content_nocontainer %}

</body>
    <footer>
    </footer>
</html>

templates/change_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{%block title%}
  Change Password
{% endblock %}

{% block content %}
    <h2> Change Your Password</h2>
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
    <button class="btn btn-outline-primary" type="submit">Change Password</button>
    </form>

{% endblock %}

templates/create_dogsitter_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    DogSitter Profile
{% endblock %}



{% block content %}
    <h1> Create Your DogSitting Profile</h1>
    <form method = "POST">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit">
    </form>
{% endblock %}

templates/edit_dog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Edit Dog Profile
{% endblock %}

{% block content %}
    <form method = "POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit">
    </form>
{% endblock %}

templates/edit_dogsitter_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Edit DogSitter Profile
{% endblock %}

{% block content %}
    <h1>{{user.first_name}} {{user.last_name}}</h1>
    <form method = "POST">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit">
    </form>
{% endblock %}

templates/edit_info.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{%block title%}
  Update Info
{% endblock %}

{% block content %}
    <h2> Update Information!</h2>
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <button class="btn btn-outline-primary" type="submit">Update Now</button>
    </form>

{% endblock %}

templates/edit_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Edit Profile
{% endblock %}

{% block content %}
    <h1>{{user.first_name}} {{user.last_name}}</h1>
    <form method = "POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="top-buttons">
    </form>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{%block title%}
   Home
{% endblock %}

{% block extra_css %}

{% load static %}
     .hero-image {
        background-image: url("{% static '/dogsitter/dogbed.jpg' %}");
    }
{% endblock %}

{% block content_nocontainer %}

<div class="hero-image">
    <div class="hero-text">
        <h1 id="title"> Daily or weekly Dogsitters in your area</h1>
        <p id="tagline"> Someone to take care of your pets as if they were their own</p>
        {% if user.is_authenticated %}
            <button class="search-button"><a href = "{% url 'search' %}"> Search Now </a></button>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Login
{% endblock %}

{% block content %}
    <form method = "POST">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="top-buttons"> Login </button>
    </form>

    <p>Don't have an account? Get one <a href = "{% url 'register' %}">here</a></p>
{% endblock %}

templates/profilepage.html
{% extends 'base.html' %}

{%block title%}
    Profile Page
{% endblock %}

{% block content_nocontainer %}

{% if profile.pk == user.profile.pk %}
{%for dog in profile.user.dog_set.all %}
    {% if dog.is_birthday_today %}
    <h3 class="birthday-msg"> Happy Birthday {{dog}}! </h3>
{% endif %}
{% endfor %}
{% endif %}


<div class="profile-page">
    <div>
        <a href="{% url 'view_gallery' profile.pk %}">
            <img class="profile-pic" src="{{ profile.image.url }}" alt="Profile Picture">
        </a>
        {% if profile.pk == user.profile.pk %}
           <a href="{% url 'add_images' %}"><p> Add photos to your photo gallery</a></p>
        {% endif %}

    </div>
    <div>
        <div class="profile-info">
            <h1 class="name">{{profile.user.first_name}} {{profile.user.last_name}}</h1>
            <p> Location: {{profile.location}} </p>
            <h4> Get to know me: </h4>
            <p>{{user.profile.bio}}</p>
            {% if profile.pk == user.profile.pk %}
            <button class="top-buttons"><a href="{% url 'edit_profile' %}">Update Profile Page</a></button>
            {% endif %}
        </div>
    </div>
</div>

{% if user.dogsitterprofile %}
    <div class="profile-additional">
        <div class="living-info">
            <p> I charge: {{user.dogsitterprofile.cost}} per day </p>
            <p> {{user.dogsitterprofile.get_housing_display}}</p>
            <p> {{user.dogsitterprofile.get_living_arrangements_display}}</h1>
            <p> Your dog will be left alone for: {{user.dogsitterprofile.get_hours_alone_display}}</p>
            {% if user.dogsitterprofile.walks == 'one' %}
                <p> Your dog will get: {{user.dogsitterprofile.get_walks_display}} walk per day </p>
            {% else %}
                <p> Your dog will get: {{user.dogsitterprofile.get_walks_display}} walks per day </p>
            {% endif %}
            <p> Your dog will sleep: {{user.dogsitterprofile.get_sleeping_arrangements_display}} at night </p>
            <p> Accepted Dog Sizes: {{user.dogsitterprofile.get_dog_sizes_display}} </p>
        </div>
    </div>
{% endif %}


    </div>
    <div>
    </div>
</div>


{% if profile.user.dog_set.exists %}
        <h1 class="dog-list">My Dogs</h1>
    {% for dog in profile.user.dog_set.all %}
        <div class="dog-section">
            <div>
                <a href="{% url 'dog_profile' dog.pk %}">
                    <img class="dog-img" src="{{ dog.image.url }}">
                </a>
            </div>
            <div>
                <h4 class="dog-info dog-name"><a href="{% url 'dog_profile' dog.pk %}"> {{dog}} </a></h4>
                <p class="dog-info"> Breed: {{dog.breed}} </p>
                <p class="dog-info"> {{dog.age}} old </p>
                <p class="dog-info">About Me: {{dog.bio|truncatewords:10}} </p>
            </div>
        </div>
    {% endfor %}
{% endif %}


{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Register
{% endblock %}

{% block content %}
    <h2> Create an Account with Dogsitters!</h2>
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="top-buttons">
    </form>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% block content %}


<form method="POST" action="{% url 'search_results' %}">
    {% csrf_token %}
    <h1> Find for your perfect dogsitter now!</h1>
    <p> Search by Location: </p>
    <input class="form-control me-2" type="search" placeholder="ex. Vancouver...." name="searched_location">
     <p> Search by Name: </p>
    <input class="form-control me-2" type="search" placeholder="ex. John Doe...." name="searched_name">
    <p> Search by Price: </p>
    <input class="form-control me-2" type="search" placeholder="ex. 15..." name="searched_cost">
    <button class="top-buttons" type="submit"> Search </button>

</form>
{% endblock %}

templates/view_dog_gallery.html
{% extends 'base.html' %}

{% block extra_css%}

.gallery-images {
    margin-top: 15px;
}

{% endblock %}

{% block content %}

{% if dog.doggalleryimage_set.exists %}
<div class="container">
    <div class="row">
    {% for doggalleryimage in dog.doggalleryimage_set.all %}
        <div class="col-md-4">
            <img src="{{ doggalleryimage.image.url }}" class="img-responsive img-thumbnail" width="350" height="350" alt="...">
       </div>
    {% endfor %}
{% else %}
<p>No more pictures yet....</p>
{% endif %}
    </div>
</div>

<div class="footer">
    <a href="{% url 'dog_profile' dog.pk %}">
        <button class="top-buttons"> Back to Profile </button>
    </a>
</div>

{% endblock %}